### ISSUE TITLE
Why Are You So Awesome?

### ISSUE THREAD

**Issue by EntropyHaos** [hhsnopek/ama#11]
# Why Are You So Awesome?

Serious and not; why?
- Is it something you eat?
- A way of thinking?
- Did you take awesome class in school?

Joking aside, you've been instrumental in my studies, any thoughts on what makes a good CS scholar, evangelist, and/or enthusiast?

_btw_ Thanks for introducing me to MarkDown and Git.

**Comment by hhsnopek** [comment]
haha because of  ☕️ and a lack of sleep

**Comment by hhsnopek** [comment]
I drink soylent, that could be a reason behind it
my thinking process is from a high level rather than low level allowing me to grasp concepts quickly
my awesome class in school... nothing particularly interesting, but so far my favorite class in school was marching band hah

jokes aside: a good CS scholar is someone who just gets the job done and learns the points that are being taught, going beyond should be done after the job/lesson is well done :)

Glad to introduce you to more than just MD and Git later down the road :)
